// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEZhQLCm0ridlzqG27bPeUBFl2Sh5qzvg',
    appId: '1:757843931817:web:abc3cb20cefa683b6a6fb8',
    messagingSenderId: '757843931817',
    projectId: 'taskmanagement-ce50d',
    authDomain: 'taskmanagement-ce50d.firebaseapp.com',
    storageBucket: 'taskmanagement-ce50d.firebasestorage.app',
    measurementId: 'G-9G3B76NQ9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnSYQKZ9pcMHu0fGSg4gw_N2enGvgNgac',
    appId: '1:757843931817:android:bfff5767963b898c6a6fb8',
    messagingSenderId: '757843931817',
    projectId: 'taskmanagement-ce50d',
    storageBucket: 'taskmanagement-ce50d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUqseTldXeTgSe6meY9ELJ1ORpj1U2ntc',
    appId: '1:757843931817:ios:5c8ba25f4e3e71596a6fb8',
    messagingSenderId: '757843931817',
    projectId: 'taskmanagement-ce50d',
    storageBucket: 'taskmanagement-ce50d.firebasestorage.app',
    iosBundleId: 'com.example.testagain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUqseTldXeTgSe6meY9ELJ1ORpj1U2ntc',
    appId: '1:757843931817:ios:5c8ba25f4e3e71596a6fb8',
    messagingSenderId: '757843931817',
    projectId: 'taskmanagement-ce50d',
    storageBucket: 'taskmanagement-ce50d.firebasestorage.app',
    iosBundleId: 'com.example.testagain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEZhQLCm0ridlzqG27bPeUBFl2Sh5qzvg',
    appId: '1:757843931817:web:d40d0c7803324bbb6a6fb8',
    messagingSenderId: '757843931817',
    projectId: 'taskmanagement-ce50d',
    authDomain: 'taskmanagement-ce50d.firebaseapp.com',
    storageBucket: 'taskmanagement-ce50d.firebasestorage.app',
    measurementId: 'G-X5YF6SMQR6',
  );
}
